name: Run Pytest

on:
  push:
    branches:
      - main # Or your main branch
  pull_request:
    branches:
      - main # Or your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Restore cached virtualenv # should cache .venv from run to run
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
          path: .venv

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pip-check
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
      
      - name: Run pytest with coverage
        run: pytest --cov=./ --cov-report=xml:coverage.xml

      - name: Run pip check
        run: |
          pip-check -a > pip-check.txt
          cat pip-check.txt

      - name: upload pip-check.txt
        uses: actions/upload-artifact@v4
        with:
          name: pip-check.txt